export function spanishPhonetic(text: string): string {
  return text
    .toLowerCase()
    .replace(/ll/g, 'y')
    .replace(/ñ/g, 'ny')
    .replace(/rr/g, 'rr (trilled r)')
    .replace(/qu(e|i)/g, 'k$1')
    .replace(/que/g, 'ke')
    .replace(/qui/g, 'ki')
    .replace(/ge|gi/g, (m) => m === 'ge' ? 'heh' : 'hee')
    .replace(/gue|gui/g, (m) => m === 'gue' ? 'ge' : 'gi')
    .replace(/ce|ci/g, (m) => m === 'ce' ? 'se' : 'si')
    .replace(/c([aouAOU])/g, 'k$1')
    .replace(/z/g, 's')
    .replace(/v/g, 'b')
    .replace(/j/g, 'h')
    .replace(/h/g, '')
    .replace(/x/g, 'ks')
    .replace(/y\b/g, 'ee')
    .replace(/([aeiouáéíóú])\s/g, '$1 ')
    .replace(/á/g, 'ah')
    .replace(/é/g, 'eh')
    .replace(/í/g, 'ee')
    .replace(/ó/g, 'oh')
    .replace(/ú/g, 'oo')
    .replace(/ü/g, 'oo')
    .replace(/[¿¡]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}
